### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by lumingzh**

### CODE REVIEW

**Comment by FineFindus** [comment]
Thanks, but the translations have been moved to [Damned Lies](https://l10n.gnome.org/module/hieroglyphic/). Sorry, I should have updated the README sooner.

**Comment by lumingzh** [comment]
> Thanks, but the translations have been moved to [Damned Lies](https://l10n.gnome.org/module/hieroglyphic/). Sorry, I should have updated the README sooner.

I know, but I can't commit the translation by Damned Lies.

The error tip: `“[Errno 128] Command: ‘['git', 'push', 'origin', 'main']’, Error: Warning: Permanently added 'github.com' (ED25519) to the list of known hosts. ERROR: Permission to FineFindus/Hieroglyphic.git denied to gnomeinfra-github. fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. ” `

**Comment by lumingzh** [comment]
https://l10n.gnome.org/vertimus/hieroglyphic/main/po/zh_CN/

**Comment by guilieb** [comment]
@lumingzh : we track this issue on GNOME’s GitLab here : https://gitlab.gnome.org/Infrastructure/damned-lies/-/issues/543#note_2225823

**Pull request closed without merging**
